export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAILURE = "FETCH_TODOS_FAILURE";
export const ADD = "ADD";
export const REMOVE = "REMOVE";
export const TOGGLE_COMPLETION = "TOGGLE_COMPLETION";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
